//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSizeHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLog
    {
        public int Id { get; set; }
        public string FullPath { get; set; }
        public string Directory { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public long FileSize { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
